task: winogrande_af_mubench
dataset_path: aialt/MuBench
dataset_name: WinoGrandeDataset_lighteval_af
output_type: multiple_choice
validation_split: null
test_split: test
doc_to_text: prompt
doc_to_target: label
doc_to_choice: choices
process_results: !function tie_handling.process_results_labeled
metric_list:
- metric: acc
  aggregation: mean
  higher_is_better: true
metadata:
  version: 1.0
