group: zeroshot_eng
task:
  - blimp_babylm_filtered
  - multiblimp_eng
  - winogrande_en_mubench
  - xstorycloze_en_mubench
  - hellaswag_en_mubench
aggregate_metric_list:
  - metric: acc
    aggregation: mean
    weight_by_size: true
metadata:
  version: 1.0
