group: zeroshot_zho
task:
  - winogrande_zh_mubench
  - xstorycloze_zh_mubench
  - hellaswag_zh_mubench
  - xcomps_zh
  - zhoblimp
  - hanzi_structure
  - hanzi_pinyin
aggregate_metric_list:
  - metric: acc
    aggregation: mean
    weight_by_size: true
metadata:
  version: 1.0
